// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.5
// source: analyzer.proto

package analyzerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ASTAnalyzer_AnalyzeAST_FullMethodName     = "/analyzer.ASTAnalyzer/AnalyzeAST"
	ASTAnalyzer_StreamProgress_FullMethodName = "/analyzer.ASTAnalyzer/StreamProgress"
)

// ASTAnalyzerClient is the client API for ASTAnalyzer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Go -> Python：将 AST 数据推送至 Python 进行分析
type ASTAnalyzerClient interface {
	// 流式发送 AST 数据对，Python 返回分析结果
	AnalyzeAST(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ASTTree, AnalyzeResult], error)
	// 订阅分析进度（Server-Side Streaming）
	StreamProgress(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressEvent], error)
}

type aSTAnalyzerClient struct {
	cc grpc.ClientConnInterface
}

func NewASTAnalyzerClient(cc grpc.ClientConnInterface) ASTAnalyzerClient {
	return &aSTAnalyzerClient{cc}
}

func (c *aSTAnalyzerClient) AnalyzeAST(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ASTTree, AnalyzeResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ASTAnalyzer_ServiceDesc.Streams[0], ASTAnalyzer_AnalyzeAST_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ASTTree, AnalyzeResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ASTAnalyzer_AnalyzeASTClient = grpc.ClientStreamingClient[ASTTree, AnalyzeResult]

func (c *aSTAnalyzerClient) StreamProgress(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ASTAnalyzer_ServiceDesc.Streams[1], ASTAnalyzer_StreamProgress_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AnalyzeRequest, ProgressEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ASTAnalyzer_StreamProgressClient = grpc.ServerStreamingClient[ProgressEvent]

// ASTAnalyzerServer is the server API for ASTAnalyzer service.
// All implementations must embed UnimplementedASTAnalyzerServer
// for forward compatibility.
//
// Go -> Python：将 AST 数据推送至 Python 进行分析
type ASTAnalyzerServer interface {
	// 流式发送 AST 数据对，Python 返回分析结果
	AnalyzeAST(grpc.ClientStreamingServer[ASTTree, AnalyzeResult]) error
	// 订阅分析进度（Server-Side Streaming）
	StreamProgress(*AnalyzeRequest, grpc.ServerStreamingServer[ProgressEvent]) error
	mustEmbedUnimplementedASTAnalyzerServer()
}

// UnimplementedASTAnalyzerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedASTAnalyzerServer struct{}

func (UnimplementedASTAnalyzerServer) AnalyzeAST(grpc.ClientStreamingServer[ASTTree, AnalyzeResult]) error {
	return status.Error(codes.Unimplemented, "method AnalyzeAST not implemented")
}
func (UnimplementedASTAnalyzerServer) StreamProgress(*AnalyzeRequest, grpc.ServerStreamingServer[ProgressEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamProgress not implemented")
}
func (UnimplementedASTAnalyzerServer) mustEmbedUnimplementedASTAnalyzerServer() {}
func (UnimplementedASTAnalyzerServer) testEmbeddedByValue()                     {}

// UnsafeASTAnalyzerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ASTAnalyzerServer will
// result in compilation errors.
type UnsafeASTAnalyzerServer interface {
	mustEmbedUnimplementedASTAnalyzerServer()
}

func RegisterASTAnalyzerServer(s grpc.ServiceRegistrar, srv ASTAnalyzerServer) {
	// If the following call panics, it indicates UnimplementedASTAnalyzerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ASTAnalyzer_ServiceDesc, srv)
}

func _ASTAnalyzer_AnalyzeAST_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ASTAnalyzerServer).AnalyzeAST(&grpc.GenericServerStream[ASTTree, AnalyzeResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ASTAnalyzer_AnalyzeASTServer = grpc.ClientStreamingServer[ASTTree, AnalyzeResult]

func _ASTAnalyzer_StreamProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AnalyzeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ASTAnalyzerServer).StreamProgress(m, &grpc.GenericServerStream[AnalyzeRequest, ProgressEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ASTAnalyzer_StreamProgressServer = grpc.ServerStreamingServer[ProgressEvent]

// ASTAnalyzer_ServiceDesc is the grpc.ServiceDesc for ASTAnalyzer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ASTAnalyzer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analyzer.ASTAnalyzer",
	HandlerType: (*ASTAnalyzerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AnalyzeAST",
			Handler:       _ASTAnalyzer_AnalyzeAST_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamProgress",
			Handler:       _ASTAnalyzer_StreamProgress_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "analyzer.proto",
}
