// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: analyzer.proto

package analyzerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AST 节点类型枚举
type NodeType int32

const (
	NodeType_NODE_TYPE_UNSPECIFIED NodeType = 0
	NodeType_NODE_TYPE_FUNCTION    NodeType = 1
	NodeType_NODE_TYPE_CLASS       NodeType = 2
	NodeType_NODE_TYPE_VARIABLE    NodeType = 3
	NodeType_NODE_TYPE_STATEMENT   NodeType = 4
	NodeType_NODE_TYPE_EXPRESSION  NodeType = 5
	NodeType_NODE_TYPE_BLOCK       NodeType = 6
	NodeType_NODE_TYPE_PARAMETER   NodeType = 7
	NodeType_NODE_TYPE_IMPORT      NodeType = 8
	NodeType_NODE_TYPE_COMMENT     NodeType = 9
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "NODE_TYPE_UNSPECIFIED",
		1: "NODE_TYPE_FUNCTION",
		2: "NODE_TYPE_CLASS",
		3: "NODE_TYPE_VARIABLE",
		4: "NODE_TYPE_STATEMENT",
		5: "NODE_TYPE_EXPRESSION",
		6: "NODE_TYPE_BLOCK",
		7: "NODE_TYPE_PARAMETER",
		8: "NODE_TYPE_IMPORT",
		9: "NODE_TYPE_COMMENT",
	}
	NodeType_value = map[string]int32{
		"NODE_TYPE_UNSPECIFIED": 0,
		"NODE_TYPE_FUNCTION":    1,
		"NODE_TYPE_CLASS":       2,
		"NODE_TYPE_VARIABLE":    3,
		"NODE_TYPE_STATEMENT":   4,
		"NODE_TYPE_EXPRESSION":  5,
		"NODE_TYPE_BLOCK":       6,
		"NODE_TYPE_PARAMETER":   7,
		"NODE_TYPE_IMPORT":      8,
		"NODE_TYPE_COMMENT":     9,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_analyzer_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_analyzer_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_analyzer_proto_rawDescGZIP(), []int{0}
}

// 语义变更类型
type ChangeType int32

const (
	ChangeType_CHANGE_TYPE_UNSPECIFIED      ChangeType = 0
	ChangeType_CHANGE_TYPE_RENAME           ChangeType = 1 // 变量/函数重命名
	ChangeType_CHANGE_TYPE_EXTRACT_FUNCTION ChangeType = 2 // 函数提取
	ChangeType_CHANGE_TYPE_CONTROL_FLOW     ChangeType = 3 // 控制流重构
	ChangeType_CHANGE_TYPE_ADD              ChangeType = 4 // 新增节点
	ChangeType_CHANGE_TYPE_DELETE           ChangeType = 5 // 删除节点
	ChangeType_CHANGE_TYPE_MOVE             ChangeType = 6 // 节点移动
)

// Enum value maps for ChangeType.
var (
	ChangeType_name = map[int32]string{
		0: "CHANGE_TYPE_UNSPECIFIED",
		1: "CHANGE_TYPE_RENAME",
		2: "CHANGE_TYPE_EXTRACT_FUNCTION",
		3: "CHANGE_TYPE_CONTROL_FLOW",
		4: "CHANGE_TYPE_ADD",
		5: "CHANGE_TYPE_DELETE",
		6: "CHANGE_TYPE_MOVE",
	}
	ChangeType_value = map[string]int32{
		"CHANGE_TYPE_UNSPECIFIED":      0,
		"CHANGE_TYPE_RENAME":           1,
		"CHANGE_TYPE_EXTRACT_FUNCTION": 2,
		"CHANGE_TYPE_CONTROL_FLOW":     3,
		"CHANGE_TYPE_ADD":              4,
		"CHANGE_TYPE_DELETE":           5,
		"CHANGE_TYPE_MOVE":             6,
	}
)

func (x ChangeType) Enum() *ChangeType {
	p := new(ChangeType)
	*p = x
	return p
}

func (x ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_analyzer_proto_enumTypes[1].Descriptor()
}

func (ChangeType) Type() protoreflect.EnumType {
	return &file_analyzer_proto_enumTypes[1]
}

func (x ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeType.Descriptor instead.
func (ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_analyzer_proto_rawDescGZIP(), []int{1}
}

// AST 单个节点
type ASTNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                // 节点唯一标识
	Type          NodeType               `protobuf:"varint,2,opt,name=type,proto3,enum=analyzer.NodeType" json:"type,omitempty"`     // 节点类型
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`                           // 节点名称（如函数名、变量名）
	StartLine     int32                  `protobuf:"varint,4,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"` // 源码起始行
	EndLine       int32                  `protobuf:"varint,5,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`       // 源码结束行
	Children      []int32                `protobuf:"varint,6,rep,packed,name=children,proto3" json:"children,omitempty"`             // 子节点 ID 列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ASTNode) Reset() {
	*x = ASTNode{}
	mi := &file_analyzer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASTNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASTNode) ProtoMessage() {}

func (x *ASTNode) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASTNode.ProtoReflect.Descriptor instead.
func (*ASTNode) Descriptor() ([]byte, []int) {
	return file_analyzer_proto_rawDescGZIP(), []int{0}
}

func (x *ASTNode) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ASTNode) GetType() NodeType {
	if x != nil {
		return x.Type
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *ASTNode) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ASTNode) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *ASTNode) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *ASTNode) GetChildren() []int32 {
	if x != nil {
		return x.Children
	}
	return nil
}

// 完整 AST 数据（一个文件版本对应一棵树）
type ASTTree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"` // 文件路径
	CommitId      string                 `protobuf:"bytes,2,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"` // Git commit SHA
	Nodes         []*ASTNode             `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`                       // 所有节点（扁平化）
	RootId        int32                  `protobuf:"varint,4,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`      // 根节点 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ASTTree) Reset() {
	*x = ASTTree{}
	mi := &file_analyzer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASTTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASTTree) ProtoMessage() {}

func (x *ASTTree) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASTTree.ProtoReflect.Descriptor instead.
func (*ASTTree) Descriptor() ([]byte, []int) {
	return file_analyzer_proto_rawDescGZIP(), []int{1}
}

func (x *ASTTree) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ASTTree) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *ASTTree) GetNodes() []*ASTNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ASTTree) GetRootId() int32 {
	if x != nil {
		return x.RootId
	}
	return 0
}

// 分析请求：指定仓库路径、文件、新旧 commit
type AnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoPath      string                 `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	OldCommit     string                 `protobuf:"bytes,3,opt,name=old_commit,json=oldCommit,proto3" json:"old_commit,omitempty"`
	NewCommit     string                 `protobuf:"bytes,4,opt,name=new_commit,json=newCommit,proto3" json:"new_commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_analyzer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_analyzer_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeRequest) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *AnalyzeRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *AnalyzeRequest) GetOldCommit() string {
	if x != nil {
		return x.OldCommit
	}
	return ""
}

func (x *AnalyzeRequest) GetNewCommit() string {
	if x != nil {
		return x.NewCommit
	}
	return ""
}

// 单条语义差异
type SemanticDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeType    ChangeType             `protobuf:"varint,1,opt,name=change_type,json=changeType,proto3,enum=analyzer.ChangeType" json:"change_type,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`        // 可读描述
	OldNode       *ASTNode               `protobuf:"bytes,3,opt,name=old_node,json=oldNode,proto3" json:"old_node,omitempty"` // 变更前节点（删除/修改时有值）
	NewNode       *ASTNode               `protobuf:"bytes,4,opt,name=new_node,json=newNode,proto3" json:"new_node,omitempty"` // 变更后节点（新增/修改时有值）
	Confidence    float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`        // 置信度 [0.0, 1.0]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticDiff) Reset() {
	*x = SemanticDiff{}
	mi := &file_analyzer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticDiff) ProtoMessage() {}

func (x *SemanticDiff) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticDiff.ProtoReflect.Descriptor instead.
func (*SemanticDiff) Descriptor() ([]byte, []int) {
	return file_analyzer_proto_rawDescGZIP(), []int{3}
}

func (x *SemanticDiff) GetChangeType() ChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ChangeType_CHANGE_TYPE_UNSPECIFIED
}

func (x *SemanticDiff) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SemanticDiff) GetOldNode() *ASTNode {
	if x != nil {
		return x.OldNode
	}
	return nil
}

func (x *SemanticDiff) GetNewNode() *ASTNode {
	if x != nil {
		return x.NewNode
	}
	return nil
}

func (x *SemanticDiff) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// 社区（强耦合模块）
type Community struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Members       []string               `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`     // 函数/类名列表
	Cohesion      float32                `protobuf:"fixed32,3,opt,name=cohesion,proto3" json:"cohesion,omitempty"` // 内聚度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Community) Reset() {
	*x = Community{}
	mi := &file_analyzer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Community) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Community) ProtoMessage() {}

func (x *Community) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Community.ProtoReflect.Descriptor instead.
func (*Community) Descriptor() ([]byte, []int) {
	return file_analyzer_proto_rawDescGZIP(), []int{4}
}

func (x *Community) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Community) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *Community) GetCohesion() float32 {
	if x != nil {
		return x.Cohesion
	}
	return 0
}

// 分析结果
type AnalyzeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diffs         []*SemanticDiff        `protobuf:"bytes,1,rep,name=diffs,proto3" json:"diffs,omitempty"`
	Communities   []*Community           `protobuf:"bytes,2,rep,name=communities,proto3" json:"communities,omitempty"`
	EditDistance  float32                `protobuf:"fixed32,3,opt,name=edit_distance,json=editDistance,proto3" json:"edit_distance,omitempty"` // 树编辑距离
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeResult) Reset() {
	*x = AnalyzeResult{}
	mi := &file_analyzer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResult) ProtoMessage() {}

func (x *AnalyzeResult) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResult.ProtoReflect.Descriptor instead.
func (*AnalyzeResult) Descriptor() ([]byte, []int) {
	return file_analyzer_proto_rawDescGZIP(), []int{5}
}

func (x *AnalyzeResult) GetDiffs() []*SemanticDiff {
	if x != nil {
		return x.Diffs
	}
	return nil
}

func (x *AnalyzeResult) GetCommunities() []*Community {
	if x != nil {
		return x.Communities
	}
	return nil
}

func (x *AnalyzeResult) GetEditDistance() float32 {
	if x != nil {
		return x.EditDistance
	}
	return 0
}

// 流式进度事件
type ProgressEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`      // 当前阶段名
	Percent       int32                  `protobuf:"varint,2,opt,name=percent,proto3" json:"percent,omitempty"` // 进度百分比 [0, 100]
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`  // 可读消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressEvent) Reset() {
	*x = ProgressEvent{}
	mi := &file_analyzer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressEvent) ProtoMessage() {}

func (x *ProgressEvent) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressEvent.ProtoReflect.Descriptor instead.
func (*ProgressEvent) Descriptor() ([]byte, []int) {
	return file_analyzer_proto_rawDescGZIP(), []int{6}
}

func (x *ProgressEvent) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *ProgressEvent) GetPercent() int32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *ProgressEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_analyzer_proto protoreflect.FileDescriptor

const file_analyzer_proto_rawDesc = "" +
	"\n" +
	"\x0eanalyzer.proto\x12\banalyzer\"\xad\x01\n" +
	"\aASTNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.analyzer.NodeTypeR\x04type\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x1d\n" +
	"\n" +
	"start_line\x18\x04 \x01(\x05R\tstartLine\x12\x19\n" +
	"\bend_line\x18\x05 \x01(\x05R\aendLine\x12\x1a\n" +
	"\bchildren\x18\x06 \x03(\x05R\bchildren\"\x85\x01\n" +
	"\aASTTree\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tcommit_id\x18\x02 \x01(\tR\bcommitId\x12'\n" +
	"\x05nodes\x18\x03 \x03(\v2\x11.analyzer.ASTNodeR\x05nodes\x12\x17\n" +
	"\aroot_id\x18\x04 \x01(\x05R\x06rootId\"\x88\x01\n" +
	"\x0eAnalyzeRequest\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x1d\n" +
	"\n" +
	"old_commit\x18\x03 \x01(\tR\toldCommit\x12\x1d\n" +
	"\n" +
	"new_commit\x18\x04 \x01(\tR\tnewCommit\"\xe3\x01\n" +
	"\fSemanticDiff\x125\n" +
	"\vchange_type\x18\x01 \x01(\x0e2\x14.analyzer.ChangeTypeR\n" +
	"changeType\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12,\n" +
	"\bold_node\x18\x03 \x01(\v2\x11.analyzer.ASTNodeR\aoldNode\x12,\n" +
	"\bnew_node\x18\x04 \x01(\v2\x11.analyzer.ASTNodeR\anewNode\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\"Q\n" +
	"\tCommunity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\amembers\x18\x02 \x03(\tR\amembers\x12\x1a\n" +
	"\bcohesion\x18\x03 \x01(\x02R\bcohesion\"\x99\x01\n" +
	"\rAnalyzeResult\x12,\n" +
	"\x05diffs\x18\x01 \x03(\v2\x16.analyzer.SemanticDiffR\x05diffs\x125\n" +
	"\vcommunities\x18\x02 \x03(\v2\x13.analyzer.CommunityR\vcommunities\x12#\n" +
	"\redit_distance\x18\x03 \x01(\x02R\feditDistance\"Y\n" +
	"\rProgressEvent\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x18\n" +
	"\apercent\x18\x02 \x01(\x05R\apercent\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*\xf8\x01\n" +
	"\bNodeType\x12\x19\n" +
	"\x15NODE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12NODE_TYPE_FUNCTION\x10\x01\x12\x13\n" +
	"\x0fNODE_TYPE_CLASS\x10\x02\x12\x16\n" +
	"\x12NODE_TYPE_VARIABLE\x10\x03\x12\x17\n" +
	"\x13NODE_TYPE_STATEMENT\x10\x04\x12\x18\n" +
	"\x14NODE_TYPE_EXPRESSION\x10\x05\x12\x13\n" +
	"\x0fNODE_TYPE_BLOCK\x10\x06\x12\x17\n" +
	"\x13NODE_TYPE_PARAMETER\x10\a\x12\x14\n" +
	"\x10NODE_TYPE_IMPORT\x10\b\x12\x15\n" +
	"\x11NODE_TYPE_COMMENT\x10\t*\xc4\x01\n" +
	"\n" +
	"ChangeType\x12\x1b\n" +
	"\x17CHANGE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CHANGE_TYPE_RENAME\x10\x01\x12 \n" +
	"\x1cCHANGE_TYPE_EXTRACT_FUNCTION\x10\x02\x12\x1c\n" +
	"\x18CHANGE_TYPE_CONTROL_FLOW\x10\x03\x12\x13\n" +
	"\x0fCHANGE_TYPE_ADD\x10\x04\x12\x16\n" +
	"\x12CHANGE_TYPE_DELETE\x10\x05\x12\x14\n" +
	"\x10CHANGE_TYPE_MOVE\x10\x062\x90\x01\n" +
	"\vASTAnalyzer\x12:\n" +
	"\n" +
	"AnalyzeAST\x12\x11.analyzer.ASTTree\x1a\x17.analyzer.AnalyzeResult(\x01\x12E\n" +
	"\x0eStreamProgress\x12\x18.analyzer.AnalyzeRequest\x1a\x17.analyzer.ProgressEvent0\x01B.Z,github.com/codediffanalyzer/proto/analyzerpbb\x06proto3"

var (
	file_analyzer_proto_rawDescOnce sync.Once
	file_analyzer_proto_rawDescData []byte
)

func file_analyzer_proto_rawDescGZIP() []byte {
	file_analyzer_proto_rawDescOnce.Do(func() {
		file_analyzer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analyzer_proto_rawDesc), len(file_analyzer_proto_rawDesc)))
	})
	return file_analyzer_proto_rawDescData
}

var file_analyzer_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_analyzer_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_analyzer_proto_goTypes = []any{
	(NodeType)(0),          // 0: analyzer.NodeType
	(ChangeType)(0),        // 1: analyzer.ChangeType
	(*ASTNode)(nil),        // 2: analyzer.ASTNode
	(*ASTTree)(nil),        // 3: analyzer.ASTTree
	(*AnalyzeRequest)(nil), // 4: analyzer.AnalyzeRequest
	(*SemanticDiff)(nil),   // 5: analyzer.SemanticDiff
	(*Community)(nil),      // 6: analyzer.Community
	(*AnalyzeResult)(nil),  // 7: analyzer.AnalyzeResult
	(*ProgressEvent)(nil),  // 8: analyzer.ProgressEvent
}
var file_analyzer_proto_depIdxs = []int32{
	0, // 0: analyzer.ASTNode.type:type_name -> analyzer.NodeType
	2, // 1: analyzer.ASTTree.nodes:type_name -> analyzer.ASTNode
	1, // 2: analyzer.SemanticDiff.change_type:type_name -> analyzer.ChangeType
	2, // 3: analyzer.SemanticDiff.old_node:type_name -> analyzer.ASTNode
	2, // 4: analyzer.SemanticDiff.new_node:type_name -> analyzer.ASTNode
	5, // 5: analyzer.AnalyzeResult.diffs:type_name -> analyzer.SemanticDiff
	6, // 6: analyzer.AnalyzeResult.communities:type_name -> analyzer.Community
	3, // 7: analyzer.ASTAnalyzer.AnalyzeAST:input_type -> analyzer.ASTTree
	4, // 8: analyzer.ASTAnalyzer.StreamProgress:input_type -> analyzer.AnalyzeRequest
	7, // 9: analyzer.ASTAnalyzer.AnalyzeAST:output_type -> analyzer.AnalyzeResult
	8, // 10: analyzer.ASTAnalyzer.StreamProgress:output_type -> analyzer.ProgressEvent
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_analyzer_proto_init() }
func file_analyzer_proto_init() {
	if File_analyzer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analyzer_proto_rawDesc), len(file_analyzer_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analyzer_proto_goTypes,
		DependencyIndexes: file_analyzer_proto_depIdxs,
		EnumInfos:         file_analyzer_proto_enumTypes,
		MessageInfos:      file_analyzer_proto_msgTypes,
	}.Build()
	File_analyzer_proto = out.File
	file_analyzer_proto_goTypes = nil
	file_analyzer_proto_depIdxs = nil
}
