# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import analyzer_pb2 as analyzer__pb2
import grpc

GRPC_GENERATED_VERSION = "1.81.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in analyzer_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ASTAnalyzerStub:
    """---- 服务定义 ----

    Go -> Python：将 AST 数据推送至 Python 进行分析
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeAST = channel.stream_unary(
            "/analyzer.ASTAnalyzer/AnalyzeAST",
            request_serializer=analyzer__pb2.ASTTree.SerializeToString,
            response_deserializer=analyzer__pb2.AnalyzeResult.FromString,
            _registered_method=True,
        )
        self.StreamProgress = channel.unary_stream(
            "/analyzer.ASTAnalyzer/StreamProgress",
            request_serializer=analyzer__pb2.AnalyzeRequest.SerializeToString,
            response_deserializer=analyzer__pb2.ProgressEvent.FromString,
            _registered_method=True,
        )


class ASTAnalyzerServicer:
    """---- 服务定义 ----

    Go -> Python：将 AST 数据推送至 Python 进行分析
    """

    def AnalyzeAST(self, request_iterator, context):
        """流式发送 AST 数据对，Python 返回分析结果"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamProgress(self, request, context):
        """订阅分析进度（Server-Side Streaming）"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ASTAnalyzerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "AnalyzeAST": grpc.stream_unary_rpc_method_handler(
            servicer.AnalyzeAST,
            request_deserializer=analyzer__pb2.ASTTree.FromString,
            response_serializer=analyzer__pb2.AnalyzeResult.SerializeToString,
        ),
        "StreamProgress": grpc.unary_stream_rpc_method_handler(
            servicer.StreamProgress,
            request_deserializer=analyzer__pb2.AnalyzeRequest.FromString,
            response_serializer=analyzer__pb2.ProgressEvent.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "analyzer.ASTAnalyzer", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("analyzer.ASTAnalyzer", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class ASTAnalyzer:
    """---- 服务定义 ----

    Go -> Python：将 AST 数据推送至 Python 进行分析
    """

    @staticmethod
    def AnalyzeAST(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            "/analyzer.ASTAnalyzer/AnalyzeAST",
            analyzer__pb2.ASTTree.SerializeToString,
            analyzer__pb2.AnalyzeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamProgress(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/analyzer.ASTAnalyzer/StreamProgress",
            analyzer__pb2.AnalyzeRequest.SerializeToString,
            analyzer__pb2.ProgressEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
